### ISSUE TITLE
Add unit tests for oof_profit calculation

### ISSUE THREAD

**Issue by iBalag** [iBalag/claimant#3]

**Comment by nchursin** [comment]
I'll pick this one up. Can't assign the issue to myself though

Could you please elaborate a bit on what oof supposed to do?

I have a test failure, but not sure I it's the test issue or the logic.

```python
      (
          datetime(2022, 3, 4), # start_oof_date
          datetime(2022, 3, 4), # start_oof_date
          20,                                # avr_salary
          # expected
          oof_profit_calculator.OOFCalculation(
              oof_profit=1,
              oof_days=1,
              oof_months=0,
              first_month_days_oof=1,
              current_month_days_oof=1
          )
      ),
```

but the output has `first_month_days_oof=0`. So I wonder if I'm getting something wrong or the logic is corrupted?

**Comment by iBalag** [comment]
Hi @nchursin ! Thanks for joining!
So, in your example you entered `start_oof_date` equals `current_date` (the second argument in `calc_oof_profit` function). So, the count of WHOLE `oof_months` will be 0, it is expected. 
The field `oof_months` shows the count of whole months between `start_oof_date` (aka last work date + 1) and current date.
For example:
start_oof_date = 10.01.2022
current_date = 4.03.2022
between these two dates we have only one whole month (February). And two edges months with not whole set of work days - January and March.
What framework are you going to use for testing? I prefer pytest ;)

**Comment by nchursin** [comment]
pytest it is :)

Ah, makes sense. Ok, thanks, I'll add some test cases and raise a PR 👍

**Comment by nchursin** [comment]
Another case I want to clarify

```python
     (
           datetime(2021, 12, 1),
           datetime(2022, 2, 28),
           20,
           oof_profit_calculator.OOFCalculation(
               oof_profit=64, # actual 63
               oof_days=64, # actual 63
               oof_months=1,
               first_month_days_oof=23,
               current_month_days_oof=20
           )
       ),
       (
           datetime(2021, 12, 1),
           datetime(2022, 1, 31),
           20,
           oof_profit_calculator.OOFCalculation(
               oof_profit=44,
               oof_days=44,
               oof_months=0,
               first_month_days_oof=23,
               current_month_days_oof=21
           )
       ),
       (
          datetime(2022, 1, 1),
          datetime(2022, 2, 28),
         20,
         oof_profit_calculator.OOFCalculation(
              oof_profit=41,
              oof_days=41,
              oof_months=0,
              first_month_days_oof=21,
              current_month_days_oof=20
         )
     )

```

In this test suite, the first test fails, but the 2nd two pass. Is this correct?

**Comment by nchursin** [comment]
Moreover, if this doesn't include year turn, then it works alright:

```
     (
         datetime(2022, 1, 1),
         datetime(2022, 3, 31),
         20,
         oof_profit_calculator.OOFCalculation(
             oof_profit=64,
             oof_days=64,
             oof_months=1,
             first_month_days_oof=21,
             current_month_days_oof=23
         )
     ),
```

**Comment by nchursin** [comment]
Ah, okay, I got it. So for all the months in between we just take the average number of days

**Comment by iBalag** [comment]
> Ah, okay, I got it. So for all the months in between we just take the average number of days

Yes, average number of work days in month is 20.
