### ISSUE TITLE
Configure Github actions to run pytest

### ISSUE THREAD

**Issue by nchursin** [iBalag/claimant#9]
I think it would be nice to cover everything with tests and make the pytest run on PRs. What do you think?

Also, do you mind adding a `Pipfile`?

**Comment by iBalag** [comment]
> I think it would be nice to cover everything with tests and make the pytest run on PRs. What do you think?
Good point :) But I have not deal with GitHub actions yet ;) If you have relevant experience - feel free to setup it.

> do you mind adding a Pipfile?
I thought about it. All my experience say me that `pyenv` with `Pipfile` is redundant in this small project. There is not benefit from it, But it takes more actions from developer and more control. It is good for big projects with big team.

**Comment by nchursin** [comment]
> Good point :) But I have not deal with GitHub actions yet ;) If you have relevant experience - feel free to setup it.

Sure, I have some experience, though not with Python. Shouldn't be much different though

> I thought about it. All my experience say me that pyenv with Pipfile is redundant in this small project. There is not benefit from it, But it takes more actions from developer and more control. It is good for big projects with big team.

Ok, sounds good. I don't have much experience with Python TBH, more with JS. And this `Pipfile` looks a lot like `package.json`, so I though it might be handy. If you think it's an overkill, let's not add that

**Comment by nchursin** [comment]
I configured the build to run pytest on pull requests and pushes to main. The config is added to the same PR as the tests, so the build is actually ran for that
